ports:
  - port: 8000
    onOpen: open-preview
  # xdebug port
  - port: 9000
    onOpen: ignore

# Commenting out. We'll run these manually in class.
#tasks:
#  - init: composer install
#    command: php -S localhost:8000 -t public/

vscode:
  extensions:
    # PHP extensions.
    - xdebug.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
